---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
panel_iframe:
  esphome:
    title: 'ESPHome'
    url: 'http://nucbox.lan:6052'
    icon: mdi:chip

mqtt:
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'

notify: !include notify.yaml

telegram_bot:
  platform: webhooks
  parse_mode: html
  api_key: !secret telegram_api
  allowed_chat_ids:
    - !secret telegram_chatid

sensor:
  - platform: github
    access_token: !secret github_token
    repositories:
      - path: 'onezero1010101/homeassistant-config'
