#- platform: instapush
#  name: instapush
#  api_key: 57b1dbbda4c48ac0a87b23c6
#  app_secret: c2a83dc950281060c4f124b9b3e104ef
#  event: msg
#  tracker: hass
- platform: telegram
  name: hassbot
  chat_id: !secret telegram_chatid
- platform: pushover
  name: pushover
  api_key: !secret pushover_apikey
  user_key: !secret pushover_userkey

