---
esphome:
  name: basement1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Basement Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Basement Humidity"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Basement1 Status"
