esphome:
  name: bedroom1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "onezero"
  password: "4518bddefd"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "3711"

ota:
sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Bedroom Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Bedroom1 Status"